#use_frameworks!
# 源文件引用(默认)
source 'https://gitee.com/kyd_iOSGroup/kyd_specs.git'

platform :ios, '8.0'

target 'KYBaseKit_Example' do
  pod 'KYBaseKit', :path => '../'

  target 'KYBaseKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
